apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
         - kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: dsolopenkov/kubia:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"