apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 4
  selector:
    app: kubia
    # type: special
  template:
    metadata:
      labels:
        app: kubia
        type: special
    spec:
      containers:
      - name: kubia
        image: dsolopenkov/kubia:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
